In [1]:
import numpy as np

with open("traindata.txt", "r") as file, open("trainlabels.txt", "r") as file1:
    x_values = np.array(())
    y_values = []
    mean=[]


    for i in range(5250):
        line = file.readline().strip() 
        tokens = line.split(',')
        count=0
      
            

            

        x_values=np.append(tokens,x_values)
        y_values.append(file1.readline().strip())
    
    # print(count) 
    # print(len(mean),"mean")
    
    # for i in range(len(x_values)):
    #     print(x_values[i][249])
    #     print(y_values[i])
    # print(x_values)
    # print()
    # print(y_values)

    # print("Total lines read:")
    # print('help')

    print(x_values)


KeyboardInterrupt: 

In [ ]:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X_train, X_test, y_train, y_test = train_test_split(x_values, y_values, stratify=y_values,random_state=1)
scaler =StandardScaler()
scaler.fit(X_train)

X_train=scaler.transform(X_train)
X_test=scaler.transform(X_test)
MLP=MLPClassifier(hidden_layer_sizes=(180,70,20),max_iter=100,batch_size=16)
MLP.fit(X_train,y_train)
# predictions =MLP.predict(x_values)
print(y_test)
prediction=[]
for i in range(len(X_test)):

    prediction.append(MLP.predict([X_test[i]])) 

['8', '14', '17', '12', '3', '11', '10', '17', '8', '18', '8', '20', '6', '12', '20', '9', '15', '1', '17', '2', '15', '10', '19', '3', '13', '15', '0', '19', '5', '6', '9', '12', '5', '6', '17', '19', '2', '10', '1', '15', '15', '16', '18', '13', '20', '18', '4', '7', '12', '6', '14', '19', '13', '12', '0', '9', '20', '5', '2', '12', '4', '2', '7', '20', '16', '3', '11', '12', '10', '13', '3', '20', '15', '14', '7', '14', '11', '8', '15', '15', '13', '20', '5', '14', '13', '19', '5', '14', '14', '8', '2', '3', '20', '2', '16', '19', '10', '13', '10', '4', '3', '8', '1', '5', '3', '13', '9', '16', '9', '19', '9', '0', '2', '9', '7', '13', '16', '3', '17', '6', '5', '6', '15', '1', '3', '14', '3', '7', '17', '20', '0', '4', '11', '11', '18', '9', '10', '2', '11', '19', '14', '16', '17', '13', '20', '3', '19', '3', '1', '16', '13', '9', '7', '16', '7', '17', '3', '17', '11', '0', '3', '15', '2', '9', '16', '14', '3', '11', '16', '15', '4', '13', '6', '11', '8', '10', '17', '7', '14', '15

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,prediction))
print(classification_report(y_test,prediction))


[[15  2  4  0  1  1  3  0  0  3  9  4  1  8  1  0  0  2  0  0  2]
 [ 3 31  0  0  0  0  3  1  0  1  1  4  0  1  5  1  2  3  3  1  1]
 [ 2  2 29  0  0  0  3  1  1  5  0  5  1  3  4  0  1  2  0  1  3]
 [ 0  1  0 28  0  9  0  0  0  4  0  2  4  0  1  0  9  1  3  0  1]
 [ 2  1  3  0 36  3  2  0  2  0  1  3  1  5  1  2  0  1  1  1  0]
 [ 2  0  1  7  1 28  0  1  0  2  3  2  6  0  3  0  5  0  3  2  0]
 [ 2  5  4  0  4  1 31  0  1  4  3  2  0  1  2  3  2  0  3  0  3]
 [ 1  4  1  0  2  1  0 37  0  0  2  1  1  1  2  0  6  2  3  0  0]
 [ 0  0  0  0  1  1  1  0 39  2  2  2  1  3  1  2  0  6  0  0  2]
 [ 4  3  3  0  1  0  0  0  0 32  1  0  9  1  1  1  1  0  2  0  3]
 [ 6  0  1  0  0  1  0  0  1  3 30  1  2  8  0  2  0  1  0  0  2]
 [ 6  1  3  0  2  2  1  1  1  1  5 19  0  2  8  2  1  0  1  0  8]
 [ 1  0  0  4  0  7  1  3  0  8  1  0 23  0  1  0  3  1  3  0  0]
 [ 5  1  3  1  0  0  1  1  1  2  5  1  1 35  2  1  0  2  2  0  1]
 [ 0  1  1  0  1  1  2  5  4  2  1  2  1  0 26  5  2  4  4  1  1]
 [ 1  0  0

In [ ]:
# param_grid = {
#     'hidden_layer_sizes': [(20, 20, 20), (30, 30, 30), (20, 50, 20)],
#     'alpha': [0.0001, 0.001, 0.01],
#     'learning_rate_init': [0.001, 0.01, 0.1],
#     'activation': ['relu', 'tanh', 'logistic'],
#     'solver': ['adam', 'sgd', 'lbfgs'],
#     'batch_size': [32, 64, 128]
# }

# # Initialize MLPClassifier
# MLP = MLPClassifier(max_iter=1000)

# # Perform grid search
# grid_search = GridSearchCV(MLP, param_grid, cv=5, n_jobs=-1)
# grid_search.fit(X_train, y_train)

# # Get the best parameters
# best_params = grid_search.best_params_
# print("Best Parameters:", best_params)

# # Evaluate on test set
# best_model = grid_search.best_estimator_
# test_accuracy = best_model.score(X_test, y_test)
# print("Test Accuracy:", test_accuracy)

In [6]:
import numpy as np

from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier


with open('traindata.txt', 'r') as file:
    # Read all lines from the file
    data = file.readlines()

for i in range(len(data)):
    parts = data[i].split(',')
    data[i] = [float(part) for part in parts]
    data[i] = np.array(data[i])

with open('trainlabels.txt', 'r') as file:
    labels = [line.strip() for line in file]

for i in range(len(labels)):
    parts = labels[i].split('\n')
    labels[i] = [int(part) for part in parts if part]


labels = [int(item) for sublist in labels for item in sublist] #removing arrayfrom each index
# print(labels)





scaler = StandardScaler()
data_standardized = scaler.fit_transform(data)

pca = PCA(n_components=2) 
principal_components = pca.fit_transform(data_standardized)

# print("Principal Components:\n", principal_components)
# print(len(principal_components))


# plt.scatter(principal_components[:, 0], principal_components[:, 1])
# plt.xlabel('Principal Component 1')
# plt.ylabel('Principal Component 2')
# plt.title('PCA Result')
# plt.show()

kmeans = KMeans(n_clusters=21)  # Choose the number of clusters
kmeans.fit(principal_components)
labels = kmeans.labels_
# print(labels)

# plt.scatter(principal_components[:, 0], principal_components[:, 1], c=labels)
# plt.xlabel('Principal Component 1')
# plt.ylabel('Principal Component 2')
# plt.title('K-means Clustering on PCA-transformed Data')
# plt.show()

X_train, X_test, y_train, y_test = train_test_split(principal_components, labels, stratify=labels,random_state=1)
# X_train=principal_components
# y_train=labels
# print(y_train)

scaler =StandardScaler()
scaler.fit(X_train)

X_train=scaler.transform(X_train)
X_test=scaler.transform(X_test)

# clf = RandomForestClassifier()
# clf.fit(X_train, y_train)

# # Predict and evaluate
# y_pred = clf.predict(X_test)
# print('Accuracy:', accuracy_score(y_test, y_pred))
MLP=MLPClassifier(hidden_layer_sizes=(180,70,20),max_iter=100,batch_size=16)
MLP.fit(X_train,y_train)
# predictions =MLP.predict(x_values)
prediction=[]
for i in range(len(X_test)):

    prediction.append(MLP.predict([X_test[i]])) 
# print(prediction)
print(prediction)
infer_labels = pd.DataFrame(prediction)
print(infer_labels)


from sklearn.metrics import classification_report,confusion_matrix
# for i in range(len(y_test)):
#     print(y_test[i])
#     print()
#     print(prediction[i])


# print(confusion_matrix(y_test,prediction))
# print(classification_report(y_test,prediction))


# print(data)

/home/vmuser/anaconda3/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


[array([6], dtype=int32), array([4], dtype=int32), array([16], dtype=int32), array([6], dtype=int32), array([13], dtype=int32), array([4], dtype=int32), array([13], dtype=int32), array([18], dtype=int32), array([4], dtype=int32), array([3], dtype=int32), array([15], dtype=int32), array([3], dtype=int32), array([5], dtype=int32), array([0], dtype=int32), array([10], dtype=int32), array([20], dtype=int32), array([10], dtype=int32), array([15], dtype=int32), array([14], dtype=int32), array([18], dtype=int32), array([18], dtype=int32), array([7], dtype=int32), array([5], dtype=int32), array([1], dtype=int32), array([8], dtype=int32), array([4], dtype=int32), array([0], dtype=int32), array([10], dtype=int32), array([13], dtype=int32), array([3], dtype=int32), array([13], dtype=int32), array([10], dtype=int32), array([20], dtype=int32), array([1], dtype=int32), array([11], dtype=int32), array([11], dtype=int32), array([16], dtype=int32), array([14], dtype=int32), array([13], dtype=int32), ar

In [2]:
import numpy as np
import pandas as pd

infer_labels = np.random.randint(0, 20, 1000)
print(infer_labels)
infer_labels = pd.DataFrame(infer_labels)

# print(infer_labels)

[ 9 19 10 13 14  5  3  2  3 10  5  1 19 12 17  8 11  7 12 12  9  1 12  0
  4  5  9 19 19 18 18 17 16 14 11  6 12  7  9  5  9 14 14 13 19  3  6  2
 14  2  2  0  6  0  9  3 11  1  9  4  1  4  4 15  6 11  9  5 19 11 16 10
  9 12  2  9 11  4  0  6  0  8 14 16 13 12  5  6 19  0 17  2  9 19 11 12
  4 12  6 19 14 18 17 10  5 17 13  2  3 10  5 11  8 14 18 15 19  5  7  9
 10 11 17 13  5 10  1 15 17 13 19 13 11  9 18 14 12 13 18 19 10 13  1  4
 18  4 17  6 18 11 19 14  7 14 14  8 13  8 12 14  7 15  2 10  6 19 13  5
 17 11 11  0 11 15  0  9  9 15  8  6 14  7 19  4  4 17  5  4 12  4  4 16
  7 12 14 17 13  0  6  9  4  3  8 14 10 15  6  6  3 16 15 17 10  6  0  3
 14  6 11 14  5  4  5  1 15 15 16  8  5  8  0 15 14 16 18  2 18 16  7 13
  4  6  8  8 11  1  5  4  5 18 18  1 13 17  6  5 16  9 12  7  8  6 12 15
 18 10 10  4 11  3  8  9  1  8 19 18 19 17  2  5  9 19 10 10 14 10 16  8
 12 15  9 14  0 12  6 11  9  4 12  8 19 13  5 12  0  9  5  2  8  8  7  3
  8  7  2  3  6  5  6 18 11  3  7  0 14 12  1  9  0